// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepositAPI.Data;

namespace RepositAPI.Migrations
{
    [DbContext(typeof(RepositDbContext))]
    [Migration("20181105215131_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RepositAPI.Models.Snippet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodeBody");

                    b.Property<int>("Language");

                    b.Property<string>("Notes");

                    b.Property<string>("Title");

                    b.Property<DateTime>("date");

                    b.HasKey("ID");

                    b.ToTable("Snippets");
                });

            modelBuilder.Entity("RepositAPI.Models.SnippetTag", b =>
                {
                    b.Property<int>("SnippetID");

                    b.Property<int>("TagID");

                    b.HasKey("SnippetID", "TagID");

                    b.HasIndex("TagID");

                    b.ToTable("SnippetTags");
                });

            modelBuilder.Entity("RepositAPI.Models.Tag", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("RepositAPI.Models.SnippetTag", b =>
                {
                    b.HasOne("RepositAPI.Models.Snippet", "Snippet")
                        .WithMany("Tags")
                        .HasForeignKey("SnippetID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RepositAPI.Models.Tag", "Tag")
                        .WithMany("Snippets")
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
